version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Seoul
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
